version: '3.6'
services:
  mariadb:
    image: ${MARIADB_IMAGE}
    mem_limit: 2gb
    command: --max_allowed_packet=134217728 --transaction-isolation=READ-UNCOMMITTED --innodb-lock-wait-timeout=10
    networks:
      stack:
        ipv4_address: 172.16.1.10
    environment:
      MYSQL_ROOT_PASSWORD: mariadbP@55
      MYSQL_DATABASE: jahia
      MYSQL_USER: jahia
      MYSQL_PASSWORD: jahia
  elasticsearch:
    image: ${ELASTICSEARCH_IMAGE}
    networks:
      stack:
        ipv4_address: 172.16.1.20
    environment:
      - discovery.type=single-node
      - cluster.name=jahia-es-cluster
    ports:
      - 9200:9200
  jahia:
    image: ${JAHIA_IMAGE}
    depends_on:
      - mariadb
    ports:
      - 8080:8080
    mem_limit: 8gb
    networks:
      stack:
        ipv4_address: 172.16.1.30
    environment:
      DBMS_TYPE: mariadb
      DB_HOST: mariadb
      DB_NAME: jahia
      DB_USER: jahia
      DB_PASS: jahia
      OPERATING_MODE: development
      PROCESSING_SERVER: 'true'
      MAX_RAM_PERCENTAGE: 95
      EXECUTE_PROVISIONING_SCRIPT: 'https://raw.githubusercontent.com/Jahia/provisioning-tutorials/main/04-jexperience/provisioning.yaml'
  jcustomer:
    image: ${UNOMI_IMAGE}
    networks:
      stack:
        ipv4_address: 172.16.1.40
    environment:
      - UNOMI_ELASTICSEARCH_ADDRESSES=elasticsearch:9200
      - UNOMI_ELASTICSEARCH_CLUSTERNAME=jahia-es-cluster
      - UNOMI_CLUSTER_PUBLIC_ADDRESS=http://localhost:8181
      - UNOMI_CLUSTER_INTERNAL_ADDRESS=https://jcustomer:9443
      - UNOMI_THIRDPARTY_PROVIDER1_IPADDRESSES=172.16.1.30
      - UNOMI_THIRDPARTY_PROVIDER1_ALLOWEDEVENTS=login,updateProperties
      - JAVA_MAX_MEM=2G
      - UNOMI_ROOT_PASSWORD=karaf
      - UNOMI_HAZELCAST_TCPIP_MEMBERS=jcustomer
      - JCUSTOMER_MAXMIND_GEOIP2_CITY_DATABASE_URL=${JCUSTOMER_MAXMIND_GEOIP2_CITY_DATABASE_URL}
    ports:
      - 9443:9443
      - 8181:8181
      - 8102:8102
    depends_on:
      - elasticsearch
networks:
  stack:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24