version: "3.8"

services:
  launch:
    container_name: apache-kylin
    image: apachekylin/apache-kylin-standalone:5.0-beta
    ports:
      - "7077:7070"
      - "8089:8088"
      - "50070:50070"
      - "8032:8032"
      - "8042:8042"
      - "2181:2181"
    deploy:
      resources:
        limits:
          memory: 8G
